service: persona-java-serverless

plugins:
  - serverless-iam-roles-per-function

custom:
  queueName: usuario-creado-queue
  topicName: usuario-creado-topic

provider:
  name: aws
  runtime: java17
  region: us-east-1
  stage: dev
  memorySize: 512
  timeout: 30
  environment:
    TABLE_NAME: personas
    QUEUE_URL: { Ref: UsuarioCreadoQueue }
    TOPIC_ARN: { Ref: UsuarioCreadoTopic }

resources:
  Resources:
    UsuarioCreadoQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.queueName}
        VisibilityTimeout: 30
    UsuarioCreadoTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:custom.topicName}

package:
  artifact: build/libs/Persona-serverless.jar

functions:
  getUsuarios:
    handler: com.example.persona.serverless.GetUsersHandler::handleRequest
    events:
      - http:
          path: usuarios/{id}
          method: get
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
        Resource: arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/personas

  createUsuario:
    handler: com.example.persona.serverless.CreateUsuarioHandler::handleRequest
    events:
      - http:
          path: usuarios
          method: post
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/personas
      - Effect: Allow
        Action:
          - sqs:SendMessage
        Resource: !GetAtt UsuarioCreadoQueue.Arn

  enviarCorreos:
    handler: com.example.persona.serverless.EnviarCorreosHandler::handleRequest
    events:
      - sqs:
          arn: !GetAtt UsuarioCreadoQueue.Arn
          batchSize: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sqs:ReceiveMessage
          - sqs:DeleteMessage
          - sqs:GetQueueAttributes
        Resource: !GetAtt UsuarioCreadoQueue.Arn
      - Effect: Allow
        Action:
          - sns:Publish
        Resource: !Ref UsuarioCreadoTopic
